---

- hosts: all
  become: true
  tasks:

    - name: install httpd and php package and update repository index
      dnf:
        name: 
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["CentOS", "Amazon", "Fedora", "RedHat"]
