---

- hosts: all
  become: true
  tasks:
    - name: update repository index
      dnf: 
        update_cache: yes
      when: ansible_distribution in ["CentOS", "Amazon", "Fedora", "RedHat"]

    - name: install httpd package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution in ["CentOS", "Amazon", "Fedora", "RedHat"]

    - name: add php suppport for apache
      dnf: 
        name: php
        state: latest
      when: ansible_distribution in ["CentOS", "Amazon", "Fedora", "RedHat"]
