---

- hosts: all
  become: true
  tasks:
    - name: update repository index
      dnf: 
        update_cache: yes

    - name: remove httpd package
      dnf:
        name: httpd
        state: absent

    - name: remove php
      dnf: 
        name: php
        state: absent
