---

- hosts: web_servers
  become: true
  pre_tasks: 


    - name: install updates (Amazon linux)
      tags: always
      dnf: 
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    - name: install updates(Ubuntu)
      tags: always
      apt: 
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: change e-mail address for admin
      tags: apache,amazon,httpd
      lineinfile: 
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "Amazon"

      #  - name: restart httpd
      #tags: apache, centos, httpd
      #service: 
      # name: httpd
      # state: restarted
      #when: httpd.changed

    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy: 
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: all
  become: true
  tasks: 
    - name: create admin user
      tags: always
      user: 
        name: admin
        groups: root
   
    - name: add ssh key for admin
      tags: always
      authorized_key: 
        user: admin
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCn248AoFKk4HXkV80AsYVfu3ZG13ac22zt5hKOzvI/XT6VD4idANjzRuUrMoq9qtF9M/o3FrcOy5zpCROS1G6UxrtWvNqlb9WMUXrpTmIIVXU1hY1PeCr9PChMK0Pmi8sH216skixu3UKB9rMHN+bGmVVEeRL6KKPgDTIsAUdwpbEWAit/1iRfpek5yCMsi1HX41Snos39Hh3N8bOE6w0femLe3doIySffwMrY3H/QJ2fMtwrW/2M6TBYrCDMPRwPbp4VCgoC1QnxSs8EIHq7WyVyWfE17wd8ymn5r4nIYv8x65IfRVUWRHcWxMobklLa+SJI4XYw95m5vl5IfoGmvMiSg4960IdekTLYofz2vKeQyT4XJYN2Gk0PL/op8vFqejxM3KmbjAXhu4/LYcvpW6IRsfp9gqE6qXNbWEJDiL0odd7b+Cj/2sXR8h5iku3yir4Dk18FJTH1QwbGHKOGCexi4bP7fyHQqfDiHYivcvzApJnFSscJQuaMMaaiLMVU= rahil@fedora"


    - name: add sudoers file for admin
      tags: always
      copy: 
        src: sudoer_admin
        dest: /etc/sudoers.d/admin
        owner: root
        group: root
        mode: 0440
