---

- hosts: web_servers
  become: true
  pre_tasks: 


    - name: install updates (Amazon linux)
      tags: always
      dnf: 
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    - name: install updates(Ubuntu)
      tags: always
      apt: 
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb (Amazon linux)
      tags: mariadb,amazon,linux,db
      dnf: 
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Amazon"
