---

- hosts: web_servers
  become: true
  pre_tasks: 


    - name: install updates (Amazon linux)
      tags: always
      dnf: 
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    - name: install updates(Ubuntu)
      tags: always
      apt: 
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy: 
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
